### ISSUE TITLE
Connection reset by peer - SSL_connect (Errno::ECONNRESET)

### ISSUE THREAD

**Issue by aphex3k** [MatthewMaker/cupertino#2]
When running `ios --trace devices:list` I get an SSL connection error. See log below

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `connect': Connection reset by peer - SSL_connect (Errno::ECONNRESET)
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `block in connect'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `connect'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:857:in `start'
        from /Library/Ruby/Gems/2.0.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:700:in `start'
        from /Library/Ruby/Gems/2.0.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:631:in `connection_for'
        from /Library/Ruby/Gems/2.0.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:994:in `request'
        from /Library/Ruby/Gems/2.0.0/gems/mechanize-2.5.1/lib/mechanize/http/agent.rb:258:in `fetch'
        from /Library/Ruby/Gems/2.0.0/gems/mechanize-2.5.1/lib/mechanize.rb:407:in `get'
        from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/agent.rb:45:in `block in get'
        from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/agent.rb:44:in `times'
        from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/agent.rb:44:in `get'
        from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/agent.rb:114:in `list_devices'
        from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/commands/devices.rb:6:in `block (3 levels) in <top (required)>'
        from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/helpers.rb:58:in `try'
        from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/commands/devices.rb:6:in `block (2 levels) in <top (required)>'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.1/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.1/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.1/lib/commander/command.rb:153:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.1/lib/commander/runner.rb:444:in `run_active_command'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.1/lib/commander/runner.rb:68:in `run!'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.1/lib/commander/delegates.rb:15:in `run!'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.1/lib/commander/import.rb:5:in `block in <top (required)>'

**Comment by aphex3k** [comment]
This seems to be an issue related to logging in via SSH. If running Terminal on the box via Screen Share it executes correctly.
